apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment-one
  template:
    metadata:
      labels:
        app: nginx-deployment-one
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: deployment-one-configmap
